language: julia
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
julia:
    - release
    - nightly
notifications:
    email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - gcc-4.8
    - g++-4.8
    
install:
  - export JULIA_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - git checkout `cat ../symengine_version.txt`

  # Setup travis for C++ library
  - source bin/install_travis.sh

  # Build C++ library
  - bin/test_travis.sh

  # Setup travis for Ruby wrappers
  - cd $JULIA_SOURCE_DIR
script:
    - gcc --version
    - g++ --version
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'
