language: julia
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
julia:
    - release
    - nightly
notifications:
    email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-4.7
    - g++-5
    - gcc-5
    
install:
  - export JULIA_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - git checkout `cat ../symengine_version.txt`
  
  exclude:
    - os: osx
  include:
    - os: linux
    - source bin/install_travis.sh
    - bin/test_travis.sh
    - cd $JULIA_SOURCE_DIR
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'
