language: julia
sudo: false
os:
  - linux
  - osx
julia:
    - release
    - nightly
notifications:
    email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-5
    
install:
  - export CXX=g++-5
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'
