language: julia
sudo: false
compiler:
  - gcc
  - clang
julia:
    - release
    - nightly
notifications:
    email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - gcc-4.8
    - g++-4.8
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'
