language: julia
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
julia:
    - release
    - nightly
    - 0.4
notifications:
    email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - gcc-5
    - g++-5
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'
